version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
          TZ: "Asia/Tokyo"
      - image: circleci/postgres:11.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: db/test.sqlite3
          POSTGRES_PASSWORD: ""
          TZ: "Asia/Tokyo"

commands:
  restore_gems:
    steps:
      - run:
          name: install Bundler
          command: gem install bundler -v 2.1.2
      - restore_cache:
          keys:
            - gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ .Branch }}
            - gem-cache
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  build_and_test:
    executor:
      name: default
    steps:
      - setup_remote_docker:
          reusable: true
      - checkout
      - restore_gems
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: rubocop
          command: |
            bundle exec rubocop -c .rubocop.yml

      - run:
          name: Lint
          command: |
            bundle exec slim-lint app/views -c config/slim_lint.yml
            bin/yarn eslint app/javascript

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - store_test_results:
          path: test_results

      - run:
          name: Run Model Test
          command: bin/rails test test/models
      - run:
          name: Run System Test
          command: bin/rails test:system
      - store_test_results:
          path: test_results

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - restore_gems
      - add_ssh_keys:
          fingerprints:
            - "3a:93:b4:ea:71:0a:e0:b5:c2:73:1e:3a:97:d3:27:5f"
      - run:
          name: Capistrano deploy
          command: bundle exec cap production deploy

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
